lib/platform_web/router.ex
defmodule PlatformWeb.Router do
  use PlatformWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug PlatformWeb.PlayerAuthController, repo: Platform.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PlatformWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/players", PlayerController
    resources "/sessions", PlayerSessionController, only: [:new, :create, :delete]
  end

  # Other scopes may use custom stacks.
  scope "/api", PlatformWeb do
    pipe_through :api
    resources "/games", GameController, except: [:new, :edit]
    resources "/gameplays", GameplayController, except: [:new, :edit]
    resources "/players", PlayerApiController, except: [:new, :edit]
  end
end

lib/platform_web/views/layout_view.ex
defmodule PlatformWeb.LayoutView do
  use PlatformWeb, :view
end

lib/platform_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>The Platform</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= csrf_meta_tag() %>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <%= if @current_user do %>
              <p class="nav-text">
                Signed in as&nbsp;
                <strong><%= link @current_user.username, to: Routes.player_path(@conn, :edit, @current_user)  %></strong>
              </p>
              <%= link "Sign Out", to: Routes.player_session_path(@conn, :delete, @current_user), method: "delete", class: "button" %>
            <% else %>
              <%= link "Sign Up", to: Routes.player_path(@conn, :new), class: "button" %>
              <%= link "Sign In", to: Routes.player_session_path(@conn, :new), class: "button" %>
            <% end %>
          </ul>
        </nav>
        <h1><%= link "Platform", to: Routes.page_path(@conn, :index), class: "logo" %></h1>
      </section> 
    </header>
    <main role="main">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>